version: "3.9"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "8080:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8282:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  web_static:
    build: docker-images/apache-php-image/.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_static.rule=Host(`test-reverse-proxy`)"

  web_dynamic:
    build: docker-images/express-image/.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_dynamic.rule=Host(`test-reverse-proxy`) && PathPrefix(`/animals`)"
      # Traefik ne retire pas automatiquement le prefix de la page lorsqu'il passe la requête au container
      - "traefik.http.routers.web_dynamic.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/animals"
      - "traefik.http.middlewares.strip-prefix.stripprefix.forceSlash=false"
  #web_dynamic:
  #  build: docker-images/express-image/.
  #  labels:
  #    - "traefik.http.routers.static.rule=Host(`test-reverse-proxy`) && Path(`/animals`)"